Wealthbot\ClientBundle\Entity\ClosingAccountHistory:
    type: entity
    table: closing_account_history
    repositoryClass: Wealthbot\ClientBundle\Repository\ClosingAccountHistoryRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        account_id:
            type: integer
            nullable: false
        messages:
            type: array
        closing_date:
            type: datetime
            nullable: false
    oneToOne:
        account:
            targetEntity: Wealthbot\ClientBundle\Entity\SystemAccount
            joinColumn:
                name: account_id
                referencedColumnName: id
                onDelete: cascade
            cascade: ['persist']