Wealthbot\ClientBundle\Entity\OneTimeContribution:
    type: entity
    table: one_time_contribution
    repositoryClass: Wealthbot\ClientBundle\Repository\OneTimeContributionRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        system_account_id:
            type: integer
            nullable: false
        bank_information_id:
            type: integer
            nullable: true
        type:
            type: string
            length: 255
        start_transfer_date:
            type: date
            nullable: true
        amount:
            type: float
            nullable: true
        contribution_year:
            type: string
            length: 4
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        systemAccount:
            targetEntity: Wealthbot\ClientBundle\Entity\SystemAccount
            joinColumn:
                name: system_account_id
                referencedColumnName: id
                onDelete: cascade
            cascade: ['persist']
        bankInformation:
            targetEntity: Wealthbot\ClientBundle\Entity\BankInformation
            joinColumn:
                name: bank_information_id
                referencedColumnName: id
                onDelete: set null
            cascade: ['persist']