rx_admin_homepage:
    path:  /admin
    defaults: { _controller: WealthbotAdminBundle:Dashboard:index }

rx_admin_login:
    path:  /admin/login
    defaults: { _controller: WealthbotAdminBundle:Secured:login }

rx_admin_login_as:
    path: /admin/login-as/{username}
    defaults: { _controller: WealthbotAdminBundle:Secured:loginAs }

rx_admin_logout:
    path:  /admin/logout
    defaults: { _controller: WealthbotAdminBundle:Secured:logout }

rx_admin_login_check:
    path:  /admin/login_check
    defaults: { _controller: WealthbotAdminBundle:Secured:loginCheck }

rx_admin_general_settings:
    path:  /admin/general-settings
    defaults: { _controller: WealthbotAdminBundle:GeneralSettings:index }

rx_admin_update_fees:
    path:  /admin/general-settings/update-fees
    defaults: { _controller: WealthbotAdminBundle:GeneralSettings:updateFees }

rx_admin_upload_documents:
    path:  /admin/general-settings/upload-documents
    defaults: { _controller: WealthbotAdminBundle:GeneralSettings:uploadDocuments }

rx_admin_custodians:
    path:  /admin/custodians
    defaults: { _controller: WealthbotAdminBundle:Custodian:index }

rx_admin_upload_custodian_documents:
    path:  /admin/custodian/{id}/upload-documents
    defaults: { _controller: WealthbotAdminBundle:Custodian:uploadDocuments }
    requirements:
        id:   \d+

rx_admin_custodian_message:
    path:  /admin/custodian/{id}/message/{type}
    defaults: { _controller: WealthbotAdminBundle:Custodian:message }
    requirements:
        id:   \d+
        type: mail_check|wire_transfer|rollover

#rx_admin_fee_new:
#    path:  /admin/fee/new
#    defaults: { _controller: WealthbotAdminBundle:GeneralSettings:newFee }
#
#rx_admin_fee_edit:
#    path:  /admin/fee/{id}/edit
#    defaults: { _controller: WealthbotAdminBundle:GeneralSettings:editFee }
#    requirements:
#        id:  \d+
#
#rx_admin_fee_delete:
#    path:  /admin/fee/{id}/delete
#    defaults: { _controller: WealthbotAdminBundle:GeneralSettings:deleteFee }
#    requirements:
#        id:  \d+

# CATEGORIES ROUTING

rx_admin_categories_index:
    path: /admin/categories/index
    defaults: { _controller: WealthbotAdminBundle:Categories:index }

rx_admin_categories_asset_delete:
    path: /admin/categories/asset/{id}/delete
    defaults: { _controller: WealthbotAdminBundle:Categories:assetDelete }

rx_admin_categories_subclass_delete:
    path: /admin/categories/subclass/{id}/delete
    defaults: { _controller: WealthbotAdminBundle:Categories:subclassDelete }

# END CATEGORIES ROUTING

# MODEL SECURITIES ROUTING

rx_admin_model_securities_list:
    path: /admin/model/{model_id}/securities/list
    defaults: { _controller: WealthbotAdminBundle:Securities:modelSecuritiesList }

rx_admin_model_securities_complete_funds:
    path: /admin/model/securities/complete-funds
    defaults: { _controller: WealthbotAdminBundle:Securities:completeFunds }

rx_admin_model_securities_complete_subclasses:
    path: /admin/model/securities/complete-subclasses
    defaults: { _controller: WealthbotAdminBundle:Securities:completeSubclasses }

rx_admin_model_securities_edit:
    path: /admin/model/securities/{id}/edit
    defaults: { _controller: WealthbotAdminBundle:Securities:editModelSecurity }

rx_admin_model_securities_delete:
    path: /admin/model/securities/{id}/delete
    defaults: { _controller: WealthbotAdminBundle:Securities:deleteModelSecurity }

# END MODEL SECURITIES ROUTING

rx_admin_subclass_new:
    path:  /admin/subclass/new
    defaults: { _controller: WealthbotAdminBundle:GeneralSettings:newSubclass }

rx_admin_subclass_edit:
    path:  /admin/subclass/{id}/edit
    defaults: { _controller: WealthbotAdminBundle:GeneralSettings:editSubclass }
    requirements:
        id:  \d+

rx_admin_subclass_delete:
    path:  /admin/subclass/{id}/delete
    defaults: { _controller: WealthbotAdminBundle:GeneralSettings:deleteSubclass }
    requirements:
        id:  \d+

rx_admin_securities:
    path:  /admin/securities
    defaults: { _controller: WealthbotAdminBundle:Securities:index }

rx_admin_securities_update_subclass:
    path:  /admin/securities/update-subclass
    defaults: { _controller: WealthbotAdminBundle:Securities:updateSubclassFormField }

rx_admin_security_new:
    path:  /admin/securities/new
    defaults: { _controller: WealthbotAdminBundle:Securities:new }

rx_admin_security_edit:
    path:  /admin/security/{id}/edit
    defaults: { _controller: WealthbotAdminBundle:Securities:edit }
    requirements:
        id:  \d+

rx_admin_security_delete:
    path:  /admin/security/{id}/delete
    defaults: { _controller: WealthbotAdminBundle:Securities:delete }
    requirements:
        id:  \d+

rx_admin_security_price_history:
    path: /admin/security/{id}/prices
    defaults: { _controller: WealthbotAdminBundle:Securities:priceHistory }

rx_admin_security_price_history_batch:
    path: /admin/security/{id}/price-history/{action}
    defaults: { _controller: WealthbotAdminBundle:Securities:priceHistoryBatch }
    requirements:
        id:  \d+
        action: delete|unpost|repost

rx_admin_models:
    path:  /admin/models
    defaults: { _controller: WealthbotAdminBundle:Model:index }

rx_admin_models_index_strategy:
    path:  /admin/models/{slug}
    defaults: { _controller: WealthbotAdminBundle:Model:indexStrategy }

rx_admin_models_create:
    path:  /admin/models/{slug}/create-model
    defaults: { _controller: WealthbotAdminBundle:Model:createModel }

rx_admin_models_update_form:
    path:  /admin/models/update-form/securities/model-entity-id/{model_entity_id}
    defaults: { _controller: WealthbotAdminBundle:Model:updateForm, model_entity_id: 0 }

rx_admin_models_edit_strategy:
    path:  /admin/models/strategy/{id}/edit
    defaults: { _controller: WealthbotAdminBundle:Model:editStrategy }
    requirements:
        id:  \d+

rx_admin_models_edit_model_assumption:
    path:  /admin/models/strategy/{id}/edit-model-assumption
    defaults: { _controller: WealthbotAdminBundle:Model:editModelAssumption }
    requirements:
        id:  \d+

rx_admin_models_delete_strategy:
    path:  /admin/models/strategy/{id}/delete
    defaults: { _controller: WealthbotAdminBundle:Model:deleteStrategy }
    requirements:
        id:  \d+

rx_admin_models_edit_model:
    path:  /admin/models/model/{id}/edit
    defaults: { _controller: WealthbotAdminBundle:Model:editModel }
    requirements:
        id:  \d+

rx_admin_models_delete_model:
    path:  /admin/models/model/{id}/delete
    defaults: { _controller: WealthbotAdminBundle:Model:deleteModel }
    requirements:
        id:  \d+

rx_admin_model_save:
    path:  /admin/model/{modelSlug}/save
    defaults: { _controller: WealthbotAdminBundle:Model:save }

rx_admin_model_delete:
    path:  /admin/model/{id}/delete
    defaults: { _controller: WealthbotAdminBundle:Model:delete }
    requirements:
        id:  \d+

rx_admin_model_edit:
    path:  /admin/model/{id}/edit
    defaults: { _controller: WealthbotAdminBundle:Model:edit }
    requirements:
        id:  \d+

rx_admin_model_schema:
    path:  /admin/models/{strategy_slug}/{model_slug}
    defaults: { _controller: WealthbotAdminBundle:Model:model }

rx_admin_risks:
    path:  /admin/risks
    defaults: { _controller: WealthbotAdminBundle:Risks:index }

rx_admin_risks_create_question:
    path:  /admin/risks/question/create
    defaults: { _controller: WealthbotAdminBundle:Risks:createQuestion }

rx_admin_risks_edit_question:
    path:  /admin/risks/question/{id}/edit
    defaults: { _controller: WealthbotAdminBundle:Risks:editQuestion }
    requirements:
        id:  \d+

rx_admin_risks_delete_question:
    path:  /admin/risks/question/{id}/delete
    defaults: { _controller: WealthbotAdminBundle:Risks:deleteQuestion }
    requirements:
        id:  \d+

rx_admin_risks_update_order:
    path:  /admin/risks/update-order
    defaults: { _controller: WealthbotAdminBundle:Risks:updateOrder }

rx_admin_ria_index:
    path:  /admin/ria/index
    defaults: { _controller: WealthbotAdminBundle:Ria:index }

rx_admin_ria_specific_dashboard:
    path:  /admin/ria/{id}/specific-dashboard
    defaults: { _controller: WealthbotAdminBundle:Ria:specificDashboard }
    requirements:
        id:  \d+

rx_admin_ria_activate:
    path:  /admin/ria/{id}/activate/{activate}
    defaults: { _controller: WealthbotAdminBundle:Ria:activate }
    requirements:
        activate: 0|1

rx_admin_ria_update_relationship :
    path: /admin/ria/{id}/update-relationship
    defaults: { _controller: WealthbotAdminBundle:Ria:updateRelationship }

rx_admin_ria_sd_settings:
    path:  /admin/ria/{ria_id}/specific-dashboard/settings
    defaults: { _controller: WealthbotAdminBundle:Ria:riaSettings }

rx_admin_ria_update_fees:
    path:  /admin/ria/{ria_id}/specific-dashboard/update-fees
    defaults: { _controller: WealthbotAdminBundle:Ria:updateFees }

rx_admin_ria_sd_save_company_profile:
    path:  /admin/ria/{ria_id}/specific-dashboard/save-company-profile
    defaults: { _controller: WealthbotAdminBundle:Ria:saveCompanyProfile }

rx_admin_ria_sd_save_marketing:
    path:  /admin/ria/{ria_id}/specific-dashboard/save-marketing
    defaults: { _controller: WealthbotAdminBundle:Ria:saveMarketing }

rx_admin_ria_sd_save_billing:
    path:  /admin/ria/{ria_id}/specific-dashboard/save-billing
    defaults: { _controller: WealthbotAdminBundle:Ria:saveBilling }

rx_admin_ria_sd_save_portfolio_management:
    path:  /admin/ria/{ria_id}/specific-dashboard/save-portfolio-management
    defaults: { _controller: WealthbotAdminBundle:Ria:savePortfolioManagement }

rx_admin_clients_index:
    path:  /admin/clients/index
    defaults: { _controller: WealthbotAdminBundle:Client:index }

rx_admin_client_specific_dashboard:
    path:  /admin/client/{id}/specific-dashboard
    defaults: { _controller: WealthbotAdminBundle:Client:specificDashboard }
    requirements:
        id:  \d+

rx_admin_client_outside_funds:
    path:  /admin/clients/account/{account_id}/outside-funds
    defaults: { _controller: WealthbotAdminBundle:Client:outsideFunds }
    requirements:
        account_id:  \d+

rx_admin_users:
    path:  /admin/users/index
    defaults: { _controller: WealthbotAdminBundle:User:index }

rx_admin_users_create_user:
    path:  /admin/users/create-user
    defaults: { _controller: WealthbotAdminBundle:User:create }

rx_admin_user_edit:
    path:  /admin/user/{id}/edit
    defaults: { _controller: WealthbotAdminBundle:User:edit }
    requirements:
        id:  \d+

rx_admin_user_delete:
    path:  /admin/user/{id}/delete
    defaults: { _controller: WealthbotAdminBundle:User:delete }
    requirements:
        id:  \d+

#############################################
# Admin billing
#############################################
rx_admin_billing:
    path:  /admin/billing/index
    defaults: { _controller: WealthbotAdminBundle:Billing:index }

rx_admin_billing_client_list:
    path:  /admin/billing/client-list/{year}/{quarter}
    defaults: { _controller: WealthbotAdminBundle:Billing:clientList }
    options:
        expose: true

rx_admin_billing_custodian_fee_file:
    path:  /admin/billing/custodian-fee-file/{year}/{quarter}
    defaults: { _controller: WealthbotAdminBundle:Billing:custodianFeeFile }
    options:
        expose: true

rx_admin_billing_summary_report:
    path:  /admin/billing/summary-report/{year}
    defaults: { _controller: WealthbotAdminBundle:Billing:summaryReport }
    options:
        expose: true
#############################################
# End admin billing
#############################################


#############################################
# Admin PAS Interfaces
#############################################
rx_admin_pas_interfaces_file_index:
    path: /admin/pas/interfaces/files
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:fileIndex }
    options:
        expose: true

rx_admin_pas_interfaces_security_index:
    path: /admin/pas/interfaces/securities
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:securityIndex }
    options:
        expose: true

rx_admin_pas_interfaces_price_index:
    path: /admin/pas/interfaces/prices
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:priceIndex }
    options:
        expose: true

rx_admin_pas_interfaces_position_index:
    path: /admin/pas/interfaces/positions
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:positionIndex }
    options:
        expose: true

rx_admin_pas_interfaces_transaction_index:
    path: /admin/pas/interfaces/transactions
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:transactionIndex }
    options:
        expose: true

rx_admin_pas_interfaces_transaction_create:
    path: /admin/pas/interfaces/transactions/create
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:transactionCreate }
    methods: [POST]
    options:
        expose: true

rx_admin_pas_interfaces_account_index:
    path: /admin/pas/interfaces/accounts
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:accountIndex }
    options:
        expose: true

rx_admin_pas_interfaces_unrealized_gain_index:
    path: /admin/pas/interfaces/unrealized-gains
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:unrealizedGainIndex }
    options:
        expose: true

rx_admin_pas_interfaces_realized_gain_index:
    path: /admin/pas/interfaces/realized-gains
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:realizedGainIndex }
    options:
        expose: true

rx_admin_pas_interfaces_trade_recon_index:
    path: /admin/pas/interfaces/trade-recon
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:tradeReconIndex }
    options:
        expose: true

rx_admin_pas_interfaces_fee_recon_index:
    path: /admin/pas/interfaces/fee-recon
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:feeReconIndex }
    options:
        expose: true

rx_admin_pas_interfaces_advisor_code_autocomplete:
    path: /admin/pas/interfaces/advisor-codes/autocomplete
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:advisorCodeAutocomplete }
    options:
        expose: true

rx_admin_pas_interfaces_transaction_type_autocomplete:
    path: /admin/pas/interfaces/transaction-types/autocomplete
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:transactionTypeAutocomplete }
    options:
        expose: true

rx_admin_pas_interfaces_security_autocomplete:
    path: /admin/pas/interfaces/securities/autocomplete
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:securityAutocomplete }
    options:
        expose: true

rx_admin_pas_interfaces_security_type_autocomplete:
    path: /admin/pas/interfaces/security-types/autocomplete
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:securityTypeAutocomplete }
    options:
        expose: true

rx_admin_pas_interfaces_account_number_autocomplete:
    path: /admin/pas/interfaces/account-numbers/autocomplete
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:accountNumberAutocomplete }
    options:
        expose: true

rx_admin_pas_interfaces_closing_method_autocomplete:
    path: /admin/pas/interfaces/closing-methods/autocomplete
    defaults: { _controller: WealthbotAdminBundle:PasInterfaces:closingMethodAutocomplete }
    options:
        expose: true
#############################################
# End admin PAS Interfaces
#############################################

#############################################
# Admin Rebalancer Interfaces
#############################################

rx_admin_rebalancer:
  path: /admin/rebalancer
  defaults: { _controller: WealthbotAdminBundle:Rebalancer:index }

rx_admin_rebalancer_history:
  path: /admin/rebalancer/history
  defaults: { _controller: WealthbotAdminBundle:Rebalancer:history }

rx_admin_rebalancer_start:
  path: /admin/rebalancer/start
  defaults: { _controller: WealthbotAdminBundle:Rebalancer:start }

rx_admin_rebalance_check_progress:
  path: /admin/rebalancer/check-progress
  defaults: { _controller: WealthbotAdminBundle:Rebalancer:checkProgress }
  options:
      expose: true
rx_admin_rebalance_post_rebalance:
  path: /admin/rebalancer/post-rebalance
  defaults: { _controller: WealthbotAdminBundle:Rebalancer:postRebalance }
  options:
      expose: true

rx_admin_rebalancer_show_details:
  path: /admin/rebalancer/show-details/client_account_value/{id}
  defaults: { _controller: WealthbotAdminBundle:Rebalancer:showDetails }

rx_admin_rebalancer_accounts_view:
  path: /admin/rebalancer/account-view/client-portfolio/{client_portfolio_id}
  defaults: { _controller: WealthbotAdminBundle:Rebalancer:accountsView }

#############################################
# End admin Rebalancer Interfaces
#############################################
