wealthbot_mailer:
    resource: "@WealthbotMailerBundle/Resources/config/routing.yml"
    prefix:   /

wealthbot_signature:
    resource: "@WealthbotSignatureBundle/Resources/config/routing.yml"
    prefix:   /signature

wealthbot_admin:
    resource: "@WealthbotAdminBundle/Resources/config/routing.yml"
    prefix:   /

wealthbot_ria:
    resource: "@WealthbotRiaBundle/Resources/config/routing.yml"
    prefix:   /

wealthbot_client:
    resource: "@WealthbotClientBundle/Resources/config/routing.yml"
    prefix:   /

WealthbotUserBundle:
    resource: "@WealthbotUserBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc