rx_user_homepage:
    path:  /
    defaults: { _controller: WealthbotUserBundle:Default:index }

rx_after_login:
    path:  /after-login
    defaults: { _controller: WealthbotUserBundle:Roles:afterLogin }

rx_ria_register:
    path: /ria/registration
    defaults: { _controller: WealthbotUserBundle:Ria:registration }

#rx_client_login_with_token:
#    path: /client/login/token/{token}/redirect-url/{redirect_url}
#    defaults: { _controller: WealthbotUserBundle:Client:loginWithToken }
#
rx_client_create_profile:
    path: /client/registration/profile
    defaults: { _controller: WealthbotUserBundle:Client:createProfile }

rx_client_register:
    path: /register
    defaults: { _controller: WealthbotUserBundle:Client:registration }

rx_client_registration:
    path: /client/registration/{ria_id}
    defaults: { _controller: WealthbotUserBundle:Client:registration }

rx_client_step2:
    path: /client/step2
    defaults: { _controller: WealthbotUserBundle:Client:step2 }

rx_client_step3:
    path: /client/step3
    defaults: { _controller: WealthbotUserBundle:Client:step3 }

rx_client_create_investment_account:
    path: /client/step3/create
    defaults: { _controller: WealthbotUserBundle:Client:createInvestmentAccount }

rx_client_add_retirement_form:
    path:  /client/add-retirement-form
    defaults: { _controller: WealthbotUserBundle:Client:addRetirementAccountForm }

rx_client_create_retirement_account:
    path: /client/step3/create-retirement
    defaults: { _controller: WealthbotUserBundle:Client:createRetirementAccount }

rx_client_create_retirement_fund:
    path: /client/step3/create-retirement-fund
    defaults: { _controller: WealthbotUserBundle:Client:createRetirementFund }

rx_client_finish_registration:
    path: /client/finish-registration
    defaults: { _controller: WealthbotUserBundle:Client:finishRegistration }

rx_search_ria:
    path:  /search-ria
    defaults: { _controller: WealthbotUserBundle:Default:searchRia }

rx_reset_user_password:
    path: /user/{user_id}/reset-password
    defaults: { _controller: WealthbotUserBundle:ChangePassword:resetPassword }
    requirements:
        user_id: \d+

rx_user_switch_to_admin:
    path: /user/switch-to-admin
    defaults: { _controller: WealthbotUserBundle:Default:switchToAdmin }

rx_complete_transfer_custodian:
    path: /complete-custodian
    defaults: { _controller: WealthbotUserBundle:Default:completeTransferCustodian }

rx_file_download:
    path: /file/logo/ria/{ria_id}
    defaults: { _controller: WealthbotUserBundle:Files:logo }

rx_download_document:
    path: /file/document/{filename}/{originalName}
    defaults: { _controller: WealthbotUserBundle:Files:documents, originalName: null }

rx_download_trade_file:
    path: /file/trade-file/{filename}/{originalName}
    defaults: { _controller: WealthbotUserBundle:Files:tradeFile, originalName: null }

rx_security_reset_password:
    path:  /forgot-password
    defaults: { _controller: WealthbotUserBundle:Security:resetPassword}