parameters:
    wealthbot_user.ria.registration.form.handler.class: Wealthbot\UserBundle\Form\Handler\RiaRegistrationFormHandler
    wealthbot_user.ria.registration.form.class: Wealthbot\UserBundle\Form\Type\RiaRegistrationType

    wealthbot_user.client.registration.form.handler.class: Wealthbot\UserBundle\Form\Handler\ClientRegistrationFormHandler
    wealthbot_user.client.registration.form.class: Wealthbot\UserBundle\Form\Type\ClientRegistrationFormType

    wealthbot_user.mailer.adv_copy.template: 'WealthbotUserBundle:Client:email.txt.twig'
    wealthbot_user.mailer.adv_copy.from_email: 'noreply@wealthbot.io'

    wealthbot_user.document_class: Wealthbot\UserBundle\Entity\Document
    wealthbot_user.subdomain_manager.class: Wealthbot\RiaBundle\Entity\RiaCompanyInformation

services:
    wealthbot_user.registration.ria.form:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: [%fos_user.registration.form.name%, "@wealthbot_user.registration.ria.form.type", null, [] ]

    wealthbot_user.registration.ria.form.type:
        class: %wealthbot_user.ria.registration.form.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ria_registration }

    wealthbot_user.registration.ria.form.handler:
        class: %wealthbot_user.ria.registration.form.handler.class%
        scope: request
        arguments: ["@wealthbot_user.registration.ria.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator", "@wealthbot.manager.fee"]

    wealthbot_user.registration.client.form:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: [%fos_user.registration.form.name%, "@wealthbot_user.registration.client.form.type", null, [] ]

    wealthbot_user.registration.client.form.type:
        class: %wealthbot_user.client.registration.form.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: client_registration }

    wealthbot_user.registration.client.form.handler:
        class: %wealthbot_user.client.registration.form.handler.class%
        scope: request
        arguments: ["@wealthbot_user.registration.client.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]


    wealthbot_user.mailer:
        class: Wealthbot\UserBundle\Mailer\TwigSwiftMailer
        arguments: ["@mailer", "@router", "@twig", { template: { adv_copy: %wealthbot_user.mailer.adv_copy.template% }, from_email: { adv_copy: %wealthbot_user.mailer.adv_copy.from_email% } }]


    wealthbot_user.update_password.form:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: [update_password_form, "@wealthbot_user.update_password.form.type", null, { validation_groups: ['password', 'ChangePassword', 'Default'] } ]

    wealthbot_user.update_password.form.type:
        class: Wealthbot\UserBundle\Form\Type\UpdatePasswordFormType
        tags:
            - { name: form.type, alias: update_password }

    wealthbot_user.update_password.form.handler:
        class: Wealthbot\UserBundle\Form\Handler\UpdatePasswordFormHandler
        scope: request
        arguments: ["@wealthbot_user.update_password.form", "@request", "@fos_user.user_manager"]

    wealthbot_user.document_manager:
        class: Wealthbot\UserBundle\Manager\DocumentManager
        arguments: ["@doctrine.orm.entity_manager", %wealthbot_user.document_class%, "@router"]

    wealthbot_user.subdomain_manager:
        class: Wealthbot\UserBundle\Manager\SubdomainManager
        arguments: ["@doctrine.orm.entity_manager", "@router", %wealthbot_user.subdomain_manager.class%, %site_domain%]

    wealthbot_user.twig.subdomain_routing_extension:
        class: Wealthbot\UserBundle\Twig\SubdomainRoutingExtension
        arguments: ["@wealthbot_user.subdomain_manager"]
        tags:
            - { name: twig.extension }

    wealthbot_user.twig.document_extension:
        class: Wealthbot\UserBundle\Twig\DocumentExtension
        arguments: ["@wealthbot_user.document_manager"]
        tags:
            - { name: twig.extension }

    wealthbot.manager.user:
        class: Wealthbot\UserBundle\Manager\UserManager
        arguments:
            - "@security.encoder_factory"
            - "@fos_user.util.username_canonicalizer"
            - "@fos_user.util.email_canonicalizer"
            - "@fos_user.entity_manager"
            - Wealthbot\UserBundle\Entity\User

    wealthbot_user.listener.serializer:
        class: Wealthbot\UserBundle\Service\SerializerSubscriber
        tags:
            - { name: jms_serializer.event_subscriber, direction: serialization, format: json }
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wealthbot_client.cash.manager"
