parameters:
    wealthbot_client.mailer.suggested_portfolio.template: 'WealthbotClientBundle:Portfolio:email.html.twig'
    wealthbot_client.mailer.close_accounts.template: 'WealthbotClientBundle:Dashboard:close_accounts_email.html.twig'
    wealthbot_client.mailer.welcome.template: 'WealthbotClientBundle:ChangeProfile:welcome_email.html.twig'
    wealthbot_client.mailer.from_email: 'noreply@wealthbot.io'
    wealthbot_client.workflow.class: '\Wealthbot\ClientBundle\Entity\Workflow'
    wealthbot.activity.class: 'Wealthbot\ClientBundle\Document\Activity'

services:
    wealthbot_client.mailer:
        class: Wealthbot\ClientBundle\Mailer\TwigSwiftMailer
        arguments:
            - "@mailer"
            - "@router"
            - "@twig"
            -
                template:
                    suggested_portfolio: %wealthbot_client.mailer.suggested_portfolio.template%
                    close_accounts: %wealthbot_client.mailer.close_accounts.template%
                    welcome: %wealthbot_client.mailer.welcome.template%
                from_email:
                    suggested_portfolio: %wealthbot_client.mailer.from_email%
                    close_accounts: %wealthbot_client.mailer.from_email%
                    welcome: %wealthbot_client.mailer.from_email%

    wealthbot_client.system_account_manager:
        class: Wealthbot\ClientBundle\Manager\SystemAccountManager
        arguments: ["@doctrine.orm.entity_manager", "@wealthbot_client.client_account_values.manager"]

    wealthbot_client.portfolio_information_manager:
        class: Wealthbot\ClientBundle\Manager\PortfolioInformationManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wealthbot.manager.fee"

    wealthbot.distribution.manager:
        class: Wealthbot\ClientBundle\Manager\DistributionManager
        arguments: ["@doctrine.orm.entity_manager"]

    wealthbot_client.contribution_form_factory:
        class: Wealthbot\ClientBundle\Form\Factory\AccountContributionFormFactory
        arguments: ["@form.factory", "@doctrine.orm.entity_manager"]

    wealthbot_client.distribution_form_factory:
        class: Wealthbot\ClientBundle\Form\Factory\DistributionFormFactory
        arguments: ["@form.factory", "@wealthbot.distribution.manager"]

    wealthbot_client.breadcrumbs_manager:
        class: Wealthbot\ClientBundle\Manager\BreadcrumbsManager
        arguments: ["@router"]

    wealthbot.workflow.manager:
        class: Wealthbot\ClientBundle\Manager\WorkflowManager
        arguments: ["@doctrine.orm.entity_manager", %wealthbot_client.workflow.class%, "@wealthbot_docusign.document_signature.manager", "@wealthbot_client.client_account_values.manager"]

    wealthbot.workflow.listener:
        class: Wealthbot\ClientBundle\EventListener\WorkflowEventListener
        arguments: ["@wealthbot.workflow.manager"]
        tags:
            - { name: kernel.event_subscriber }

    wealthbot.workflow.extension:
        class: Wealthbot\ClientBundle\Twig\WorkflowTwigExtension
        arguments: ["@wealthbot.workflow.manager", "@wealthbot_user.document_manager"]
        tags:
            - { name: twig.extension }


    wealthbot_client.slave_client.form:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: [slave_client_form, "@wealthbot_client.slave_client.form.type" ]

    wealthbot_client.slave_client.form.type:
        class: Wealthbot\ClientBundle\Form\Type\SlaveClientFormType
        tags:
            - { name: form.type, alias: slave_client }

    wealthbot_client.slave_client.form.handler:
        class: Wealthbot\ClientBundle\Form\Handler\SlaveClientFormHandler
        scope: request
        arguments: ["@wealthbot_client.slave_client.form", "@request", "@doctrine.orm.entity_manager", "@wealthbot.mailer"]

    wealthbot_client.acl:
        class: Wealthbot\ClientBundle\Model\Acl
        arguments: ["@service_container"]

    wealthbot_client.transfer_screen_step.manager:
        class: Wealthbot\ClientBundle\Manager\TransferScreenStepManager
        arguments: ["@wealthbot_docusign.account_docusign.manager"]

    wealthbot_client.activity_summary.manager:
        class: Wealthbot\ClientBundle\Manager\ActivitySummaryManager
        arguments: ["@doctrine.orm.entity_manager"]

    wealthbot_client.client_portfolio.manager:
        class: Wealthbot\ClientBundle\Manager\ClientPortfolioManager
        arguments: ["@doctrine.orm.entity_manager", "@wealthbot_admin.ce_model_manager"]

    wealthbot_client.client_portfolio_values.manager:
        class: Wealthbot\ClientBundle\Manager\ClientPortfolioValuesManager
        arguments: ["@doctrine.orm.entity_manager", "@wealthbot.manager.user"]

    wealthbot_client.client_account_values.manager:
        class: Wealthbot\ClientBundle\Manager\ClientAccountValuesManager
        arguments: ["@doctrine.orm.entity_manager", "@wealthbot.manager.user"]

    wealthbot_client.client_allocation_values.manager:
        class: Wealthbot\ClientBundle\Manager\ClientAllocationValuesManager
        arguments: ["@doctrine.orm.entity_manager", "@wealthbot_client.system_account_manager"]

    wealthbot_client.cash.manager:
        class: Wealthbot\ClientBundle\Manager\CashCalculationManager
        arguments:
            - "@doctrine.orm.entity_manager"

    wealthbot_client.doctrine.subscriber:
        class: Wealthbot\ClientBundle\Service\DoctrineSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            
    wealthbot.activity.manager:
        class: Wealthbot\ClientBundle\Manager\ActivityManager
        arguments: ["@doctrine.odm.mongodb.document_manager", %wealthbot.activity.class%, "@wealthbot.workflow.manager"]
