parameters:
    wealthbot_docusign.connection:
        username:       %docusign_username%
        password:       %docusign_password%
        integratorKey:  %docusign_integrator_key%
        brand_id:       %docusign_brand_id%
        #account_id:     350278
    wealthbot_docusign.templates:
        personal_account:               %docusign_personal_account%
        ira_account:                    %docusign_ira_account%
        electronic_funds_transfer_form: %docusign_electronic_funds_transfer_form%
        account_transfer_form:          %docusign_account_transfer_form%
        check_request:                  %docusign_check_request%
        wire_instructions:              %docusign_wire_instructions%
        ira_distribution_form:          %docusign_ira_distribution_form%
        beneficiary_designation_form:   %docusign_beneficiary_designation_form%

    wealthbot_docusign.api_client.class: Wealthbot\SignatureBundle\Docusign\DocusignSessionPersistence
    wealthbot_docusign.account_docusign.class: Wealthbot\ClientBundle\Entity\ClientAccountDocusign
    wealthbot_docusign.account_signature.class: Wealthbot\SignatureBundle\Entity\DocumentSignature
    wealthbot_docusign.account_owner_signature.class: Wealthbot\SignatureBundle\Entity\DocumentOwnerSignature

services:
    wealthbot_docusign.account_docusign.manager:
        class: Wealthbot\SignatureBundle\Manager\AccountDocusignManager
        arguments: ["@doctrine.orm.entity_manager", %wealthbot_docusign.account_docusign.class%]

    wealthbot_docusign.document_signature.manager:
        class: Wealthbot\SignatureBundle\Manager\DocumentSignatureManager
        arguments: ["@doctrine.orm.entity_manager", %wealthbot_docusign.account_signature.class%, %wealthbot_docusign.account_owner_signature.class%]

    wealthbot_docusign.api_client:
        class: %wealthbot_docusign.api_client.class%
        arguments: [%wealthbot_docusign.connection%, "@session"]

    wealthbot_docusign.electronic_signature_service:
        class: Wealthbot\SignatureBundle\Service\ElectronicSignatureService
        arguments: ["@wealthbot_docusign.api_client", "@wealthbot_docusign.document_signature.manager", "@wealthbot_docusign.account_docusign.manager", %wealthbot_docusign.templates%]

    wealthbot_user.twig.signature_extension:
        class: Wealthbot\SignatureBundle\Twig\SignatureTwigExtension
        arguments: ["@wealthbot_docusign.document_signature.manager"]
        tags:
            - { name: twig.extension }
