parameters:
    wealthbot_ria.mailer.confirmation.template: 'WealthbotRiaBundle:Client:email.txt.twig'
    wealthbot_ria.mailer.bill_report.template: 'WealthbotRiaBundle:Billing/Report:bill_email.html.twig'
    wealthbot_ria.mailer.confirmation.from_email: 'noreply@wealthbot.io'
    wealthbot_ria.mailer.invite.template: 'WealthbotRiaBundle:Prospects:email.txt.twig'
    wealthbot_ria.mailer.invite.from_email: 'noreply@wealthbot.io'
    wealthbot_ria.ce_model_class: '\Wealthbot\AdminBundle\Entity\CeModel'
#    wealthbot_ria.example.class: Wealthbot\RiaBundle\Example

services:
    wealthbot_ria.mailer:
        class: Wealthbot\RiaBundle\Mailer\TwigSwiftMailer
        arguments:
            - "@mailer"
            - "@router"
            - "@twig"
            -
                template:
                    confirmation: %wealthbot_ria.mailer.confirmation.template%
                    bill_report: %wealthbot_ria.mailer.bill_report.template%
                from_email:
                    confirmation: %wealthbot_ria.mailer.confirmation.from_email%

    wealthbot_ria.mailer.invite:
        class: Wealthbot\RiaBundle\Mailer\TwigSwiftMailer
        arguments: ["@mailer", "@router", "@twig", { template: { invite: %wealthbot_ria.mailer.invite.template% }, from_email: { invite: %wealthbot_ria.mailer.invite.from_email% } }]
#    wealthbot_ria.mailer.not_finished_registration:
#        class: Wealthbot\RiaBundle\Mailer\TwigSwiftMailer
#        arguments: [@mailer, @router, @twig, { template: {not_finished_registration: }}]
    wealthbot_ria.flash_listener:
        class: Wealthbot\RiaBundle\EventListener\FlashListener
        arguments: ["@session"]
        tags:
            - { name: kernel.event_subscriber }


#    wealthbot_ria.example:
#        class: %wealthbot_ria.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    wealthbot_ria.validator.user_password:
        class: Wealthbot\RiaBundle\Validator\Constraint\CurrentPasswordValidator
        arguments: ["@wealthbot_client.acl", "@security.encoder_factory"]
        tags:
            - { name: validator.constraint_validator, alias: wealthbot_ria.validator.user_password }

    wealthbot_ria.doctrine.subscriber:
        class: Wealthbot\RiaBundle\Service\DoctrineSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # Ria manager
    wealthbot_ria.summary_information.manager:
        class: Wealthbot\RiaBundle\Service\Manager\SummaryInformationManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wealthbot_client.cash.manager"
            - "@wealthbot_ria.period.manager"
            - "@translator.default"

    wealthbot_ria.period.manager:
        class: Wealthbot\RiaBundle\Service\Manager\PeriodManager

    wealthbot_ria.billing_report.manager:
        class: Wealthbot\RiaBundle\Service\Manager\BillingReportManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@twig"
            - "@wealthbot_ria.summary_information.manager"
            - "@wealthbot.manager.fee"
            - "@wealthbot_ria.period.manager"

    # Ria security
    wealthbot_ria.security.voter.ria_client:
        class: Wealthbot\RiaBundle\Service\Security\Voter\RiaClientVoter
        public: false
        tags:
            - { name: security.voter }

    wealthbot_ria.security.voter.billing_spec:
        class: Wealthbot\RiaBundle\Service\Security\Voter\BillingSpecVoter
        public: false
        tags:
            - { name: security.voter }

    wealthbot_ria.security.voter.bill_item:
        class: Wealthbot\RiaBundle\Service\Security\Voter\BillItemVoter
        public: false
        tags:
            - { name: security.voter }

    wealthbot_ria.security.voter.client_account:
        class: Wealthbot\RiaBundle\Service\Security\Voter\ClientAccountVoter
        public: false
        tags:
            - { name: security.voter }
